web:
  image: nginx:1.21.6
  ports:
    - "8080:80"
  volumes:
    - ./code:/code
    - ./site.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
php:
  image: php:8.1-fpm-bullseye
  volumes:
    - ./code:/code
    - ./php.ini:/usr/local/etc/php/conf.d/php.ini
  environment:
    APP_LOG_DIR: /tmp
